### ISSUE TITLE
Uploaded 500-classes pretrained models are maybe incorrect (no trained)

### ISSUE THREAD

**Issue by TylorShine** [auspicious3000/contentvec#10]
Hello, thanks for your great work.

As above in the title, The 500-classes pre-trained models were probably not trained.

# Detail
I have tried to extract features with using pre-trained 500-classes legacy model (`checkpoint_best_legacy_500.pt`).  
But I compared this extracted feature to the HuBERT base model one with output graph, seems to be same.  

Here is a example input as same sound:

HuBERT (fairseq officially pre-trained hubert_base.pt)
![embeddings-1682615961-hubert-0-hubert_base](https://user-images.githubusercontent.com/62419696/235013184-966cdd63-536e-4f23-b69c-993ac129a77c.png)

ContentVec (checkpoint_best_legacy_500.pt)  
![embeddings-1682615935-hubert-0_contentvec](https://user-images.githubusercontent.com/62419696/235013827-5659ce79-f753-4b8b-99e3-8f525647218f.png)
(title is "hubert", but this is truly "checkpoint_best_legacy_500.pt"'s output)  

And, I wrote a script for compare model's state_dict [(gist)](https://gist.github.com/TylorShine/dd406ff2a576f8f44b5a04d7ce7fd8bf).
In this result, `hubert_base.pt` and `checkpoint_best_legacy_500.pt` are the same.  
This is same that `checkpoint_best_500.pt`, additional key is maybe correct for (pre-)training the ContentVec but other `hubert_base.pt` related keys' values are same.  

Just to be sure, I also checked the 100-classes pre-trained models named `checkpoint_best_{legacy_|}100.pt`, which was seems to trained correctly.

If it exists, could you please upload the correct one?

Regards.

**Comment by auspicious3000** [comment]
I used your code to compare the hubert_base and checkpoint_best_legacy_500, and your code printed "Differ Some Values!" all over the screen.

**Comment by TylorShine** [comment]
Thanks fast replying.

I'm sorry, You are right. conclusions:
- `checkpoint_best_500.pt` and `checkpoint_best_legacy_500.pt` where you uploaded files are *no problem*. It's fine.
- I misread that [this file uploaded by 3rd person to the Huggingface](https://huggingface.co/lj1995/VoiceConversionWebUI/blob/main/hubert_base.pt) is mirror of [this HuBERT Base](https://github.com/facebookresearch/fairseq/tree/main/examples/hubert) and pruned some weights. I wrote another [gist (torch only version of previous comparing script)](https://gist.github.com/TylorShine/3d8e9e8b085f4c9d3e2c8f863bf0c562) and verifying that a `hubert_base.pt` file's weights, it has the same weights as the ContentVec `checkpoint_best_500.pt`, no way.
  - This is very confusing, I'll try to contact to that uploader. (or is it your job?)

Again, thank you for your wonderful work. I'll take a break.

**Comment by auspicious3000** [comment]
So far, this is the only official repo for contentvec. We have not uploaded our models to other places.

**Comment by TylorShine** [comment]
OK, I understand. Thanks for given your time to me!

Have a nice day!
