### ISSUE TITLE
issue about forward_padding_mask

### ISSUE THREAD

**Issue by zhenye234** [auspicious3000/contentvec#12]
Hello, thanks for your great work.

I am confused about  minus 400 here
https://github.com/auspicious3000/contentvec/blob/d746688a32940f4bee410ed7c87ec9cf8ff04f74/contentvec/models/hubert/contentvec.py#L500
May I know why?

**Comment by auspicious3000** [comment]
400 is the frame length, and 320 is the frame shift
this code is for batch generation only, which is rarely used

**Comment by zhenye234** [comment]
Thank you for your reply.
