### ISSUE TITLE
Question about released model and speaker information

### ISSUE THREAD

**Issue by asr-pub** [auspicious3000/contentvec#15]
Hello, Thank for your great work. 
1. The released model were trained on LibriSpeech 960hrs ?
2. In the paper, the teachers are discrete semantic tokens, How to measure the Speaker info. in teachers ? 
![image](https://github.com/auspicious3000/contentvec/assets/22003430/e22c973f-0943-4552-8de2-8cc1b726bcac)

**Comment by auspicious3000** [comment]
This is only a conceptual curve of how speaker information changes through the network layers. You can roughly "measure" the speaker information by, for example, measuring the speaker classification accuracy.

**Comment by asr-pub** [comment]
> This is only a conceptual curve of how speaker information changes through the network layers. You can roughly "measure" the speaker information by, for example, measuring the speaker classification accuracy.

OK, Thank u
