### ISSUE TITLE
Question about speaker embedding

### ISSUE THREAD

**Issue by TechInterMezzo** [auspicious3000/contentvec#17]
The extract_features method of the ContentVec model (not the legacy one) needs speaker embedding as a parameter.
So do I have to get the speaker embedding (with Resemblyzer) for every audio sample I pass to ContentVec?

**Comment by auspicious3000** [comment]
No. You can pass zero vectors.

**Comment by TechInterMezzo** [comment]
Sorry, I have to reopen this.
If I pass zero vectors as speaker embedding there are no errors but the output is also zero vectors.
If the speaker embedding is only made of ones instead of zeros I get output with non zero vectors.
Did I overlook something?
Is there an inference example of the current model?

**Comment by auspicious3000** [comment]
please check if the target layer is below or at the 12th layer.

**Comment by TechInterMezzo** [comment]
You are right, that was my fault.
I think I have to reread the paper to understand the reason behind that.
