### ISSUE TITLE
how to convert checkpoint_best_500.pt to checkpoint_best_legacy_500.pt  model

### ISSUE THREAD

**Issue by kwaihua** [auspicious3000/contentvec#30]
Hello, I have pretrained a model using your code, but I would like to convert it to a legacy model. But I didn't see the conversion code, could you help me? Thank you very much.

**Comment by auspicious3000** [comment]
```
import torch
from fairseq.file_io import PathManager

with PathManager.open('checkpoint_best.pt', "rb") as f:
    old_state = torch.load(f, map_location=torch.device("cpu"))
    print(old_state.keys())
    
    old_state['cfg']['task'].pop('crop')
    old_state['cfg']['task'].pop('spk2info')
    old_state['cfg']['task']['_name'] = 'hubert_pretraining'
    old_state['cfg']['task']['data'] = 'metadata'
    old_state['cfg']['task']['label_dir'] = 'label'
    old_state['cfg']['model']['_name'] = 'hubert'
    old_state['cfg']['criterion']['_name'] = 'hubert'
    
    print(old_state['cfg'])
    
    old_state['optimizer_history'][0]['criterion_name'] = 'HubertCriterion'
    print(old_state['optimizer_history'])
    
    for key in remove_keys:
        old_state['model'].pop(key)
    
    with PathManager.open('checkpoint_best_legacy_500.pt', "wb") as f1:
        torch.save(old_state, f1)
```

**Comment by kwaihua** [comment]
> ```
> import torch
> from fairseq.file_io import PathManager
> 
> with PathManager.open('checkpoint_best.pt', "rb") as f:
>     old_state = torch.load(f, map_location=torch.device("cpu"))
>     print(old_state.keys())
>     
>     old_state['cfg']['task'].pop('crop')
>     old_state['cfg']['task'].pop('spk2info')
>     old_state['cfg']['task']['_name'] = 'hubert_pretraining'
>     old_state['cfg']['task']['data'] = 'metadata'
>     old_state['cfg']['task']['label_dir'] = 'label'
>     old_state['cfg']['model']['_name'] = 'hubert'
>     old_state['cfg']['criterion']['_name'] = 'hubert'
>     
>     print(old_state['cfg'])
>     
>     old_state['optimizer_history'][0]['criterion_name'] = 'HubertCriterion'
>     print(old_state['optimizer_history'])
>     
>     for key in remove_keys:
>         old_state['model'].pop(key)
>     
>     with PathManager.open('checkpoint_best_legacy_500.pt', "wb") as f1:
>         torch.save(old_state, f1)
> ```

Thank you very much, it has been very helpful to me!

**Comment by bzp83** [comment]
just found this code, but I'm getting this error:

Traceback (most recent call last):
  File "convert_to_legacy.py", line 21, in <module>
    for key in remove_keys:
NameError: name 'remove_keys' is not defined

could you pls help me fix this?

thanks!
