### ISSUE TITLE
How to get  lo, hi of spk2info in onwn dataset

### ISSUE THREAD

**Issue by k-washi** [auspicious3000/contentvec#7]
I would like to do the training on my own dataset, but I could not figure out how to create the lo, hi information in spk2info.
lo is mini pitch, hi is max pitch？
How do you extract the pitch?

**Comment by auspicious3000** [comment]
Yes, the lo, and hi are empirically determined for males and females respectively with minor tweaks for some specific speakers. They are not determined from the extracted pitch, but you can do that to get more accurate lo and hi.
